server:
  port: 9990
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: 13.82.103.66
      port: 8500
  datasource:
    driver-class: com.microsoft.sqlserver.jdbc.SQLserverDriver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update

---

