server:
  port: 9990
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: 13.82.103.66
      port: 8500
#    gateway:
#      routes:
#        - id: market-service
#            uri: lb://market-service
#            predicates:
#              - Path=/items/**
#            # If our uri is more complicated and we want to strip part of the predicate, we can use a filter.
#            # filters:
#            #     - StripPrefix=1
#        - id: cart-service
#            uri: lb://market-service
#            predicates:
#              - Path=/shopping-cart/**
