server:
  port: 9990
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: 13.82.103.66
      port: 8500
    gateway:
      routes:
        - id: batch-service
          uri: lb://batch-service
          predicates:
            - Path=/batches/**
        - id: curriculum-service
          uri: lb://curriculum-service
          predicates:
            - Path=/curriculum/**
            - Path=/batch-days/**
    #        - id: curriculum-service
    #            uri: lb://curriculum-service
    #            predicates:
    #              - Path=/batch-days/**
  datasource:
    driver-class: com.microsoft.sqlserver.jdbc.SQLserverDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update



---

server:
  port: 9990
spring:
  application:
    name: gateway-service-dev
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: batch-service
          uri: lb://batch-service-8083
          predicates:
            - Path=/batches/**
        - id: curriculum-service
          uri: lb://curriculum-service
          predicates:
            - Path=/curriculum/**
            - Path=/batch-days/**
      #        - id: curriculum-service
      #            uri: lb://curriculum-service
      #            predicates:
      #              - Path=/batch-days/**
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class: com.microsoft.sqlserver.jdbc.SQLserverDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update