server:
  port: 9990
#  servlet:
#    context-path: /test
spring:
  application:
    name: gateway-service
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#    gateway:
#      routes:
#        - id: market-service
#            uri: lb://market-service
#            predicates:
#              - Path=/items/**
#            # If our uri is more complicated and we want to strip part of the predicate, we can use a filter.
#            # filters:
#            #     - StripPrefix=1
#        - id: cart-service
#            uri: lb://market-service
#            predicates:
#              - Path=/shopping-cart/**
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    driver-class: com.microsoft.sqlserver.jdbc.SQLserverDriver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create